### ISSUE TITLE
Spinner keeps loading after moving away from Home tab

### ISSUE THREAD

**Issue by SChakravorti21** [SChakravorti21/SakaiClientAndroid#3]
Upon the first time the app loads, if the user moves away from the home page before the `HomeFragment` is added to the `FrameLayout`, the spinner keeps spinning. This is probably because the spinner is tied to the activity and not the fragment. Two things need to be done to fix this issue:
- [ ] Move the initial call to `DataHandler.requestAllSites` to `HomeFragment`
- [ ] Make the spinner belong to the `HomeFragment` instead of the `NavActivity`

**Comment by SChakravorti21** [comment]
This has become a non-issue since requests are being made in the NavActivity from now on. To fix this, all that needs to be done is setting the spinner's visibility to none in onNavigationItemSelected

**Comment by SChakravorti21** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spinner keeps loading after moving away from Home tab #3](https://trello.com/c/0dxuz9RI/4-spinner-keeps-loading-after-moving-away-from-home-tab-3)

**Comment by SChakravorti21** [comment]
After reconsideration, this is actually a slightly larger problem. If the user moves away from the `Home Fragment` while it loads for the first time, whatever tab they go to will not have the base `Course` list to organize their layouts. This will cause the app to crash almost immediately. To mitigate the issue, we should probably prevent the user from moving away from the `Home` tab while it loads, possibly disabling the other `BottomNavigationBar` buttons. @akench Can you look into handling this?

**Comment by akench** [comment]
sure,

**Comment by SChakravorti21** [comment]
Yea that's a good idea, makes it more obvious that they need to wait for home to load before doing anything else.

**Comment by SChakravorti21** [comment]
This has been fixed by @akench in PR #19 for `BottomNavigationBar` refinements, which disables other navigation items if all courses are being loaded or they fail to load.
